extends = 'blank'
[strip-0]
label = "PhysStrip0"

[strip-1]
label = "PhysStrip1"

[strip-2]
label = "PhysStrip2"

[strip-3]
label = "VirtStrip0"

[strip-4]
label = "VirtStrip1"

[bus-0]
label = "PhysBus0"

[bus-1]
label = "PhysBus1"

[bus-2]
label = "PhysBus2"

[bus-3]
label = "VirtBus0"

[bus-4]
label = "VirtBus1"
