# load with themes enabled? set the default mode
[theme]
enabled=true
mode="light"
# load in extended mode? if so which orientation
[extends]
extended=true
extends_horizontal=true
# default dimensions for channel label frames
[channel]
width=80
height=130
# default submix bus (0-7 corresponding to A1,A2..B2,B3)
[submixes]
default=0
